# Generated by Django 3.2.8 on 2021-11-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toiletlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='clean',
            field=models.IntegerField(choices=[(0, 'すごく綺麗'), (1, 'やや綺麗'), (2, 'やや汚い'), (3, 'すごく汚い')], default=0),
        ),
        migrations.AddField(
            model_name='toilet',
            name='sex',
            field=models.IntegerField(choices=[(0, '共用トイレ'), (1, '男子トイレ'), (2, '女子トイレ')], default=0),
        ),
        migrations.AddField(
            model_name='toilet',
            name='type',
            field=models.IntegerField(choices=[(0, '洋式トイレ'), (1, '和式トイレ'), (2, '両方あり')], default=0),
        ),
        migrations.AddField(
            model_name='toilet',
            name='washlet',
            field=models.IntegerField(choices=[(0, 'ウォシュレットあり'), (1, 'ウォシュレットなし'), (2, '両方あり')], default=0),
        ),
    ]
