# Generated by Django 3.2.8 on 2021-11-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toiletlog', '0002_auto_20211102_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
