# Generated by Django 3.2.8 on 2021-11-03 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toiletlog', '0003_toilet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='タイトル'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toilet',
            name='address',
            field=models.CharField(max_length=255, verbose_name='番地'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='building',
            field=models.CharField(blank=True, max_length=255, verbose_name='建物名'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='city',
            field=models.CharField(max_length=255, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='clean',
            field=models.IntegerField(choices=[(0, 'すごく綺麗'), (1, 'やや綺麗'), (2, 'やや汚い'), (3, 'すごく汚い')], default=0, verbose_name='綺麗さ'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='トイレ画像'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='info',
            field=models.TextField(blank=True, max_length=1000, verbose_name='情報'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='prefecture',
            field=models.IntegerField(choices=[(0, '--'), (1, '北海道'), (2, '青森県'), (3, '岩手県'), (4, '宮城県'), (5, '秋田県'), (6, '山形県'), (7, '福島県'), (8, '茨城県'), (9, '栃木県'), (10, '群馬県'), (11, '埼玉県'), (12, '千葉県'), (13, '東京都'), (14, '神奈川県'), (15, '新潟県'), (16, '富山県'), (17, '石川県'), (18, '福井県'), (19, '山梨県'), (20, '長野県'), (21, '岐阜県'), (22, '静岡県'), (23, '愛知県'), (24, '三重県'), (25, '滋賀県'), (26, '京都府'), (27, '大阪府'), (28, '兵庫県'), (29, '奈良県'), (30, '和歌山県'), (31, '鳥取県'), (32, '島根県'), (33, '岡山県'), (34, '広島県'), (35, '山口県'), (36, '徳島県'), (37, '香川県'), (38, '愛媛県'), (39, '高知県'), (40, '福岡県'), (41, '佐賀県'), (42, '長崎県'), (43, '熊本県'), (44, '大分県'), (45, '宮崎県'), (46, '鹿児島県'), (47, '沖縄県')], default=0, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='sex',
            field=models.IntegerField(choices=[(0, '共用トイレ'), (1, '男子トイレ'), (2, '女子トイレ')], default=0, verbose_name='何トイレ'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='type',
            field=models.IntegerField(choices=[(0, '洋式トイレ'), (1, '和式トイレ'), (2, '両方あり')], default=0, verbose_name='種類'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='washlet',
            field=models.IntegerField(choices=[(0, 'ウォシュレットあり'), (1, 'ウォシュレットなし'), (2, '両方あり')], default=0, verbose_name='ウォシュレット'),
        ),
    ]
